stages:
  - prepare
  - test

variables:
  MQ_CONN_STRING: "amqp://guest:guest@172.16.27.7/"
  DEBUG: "1"

before_script:
  - whoami
  - docker info


build:
  stage: prepare
  script:
    - docker build -t logger-client .

test: 
  stage: test
  script:
    - docker run --rm logger-client go test


after_script:
  - docker rmi logger-client