image: docker:latest

stages:
  - test

variables:
  MQ_CONN_STRING: "amqp://guest:guest@172.16.27.7/"
  DEBUG: "1"
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - docker info

test: 
  stage: test
  script:
    - whoami
    - docker-compose up

after_script:
  - docker-compose rm -f | true