stages:
  - test

before_script:
  - whoami
  - docker info

test: 
  stage: test
  script:
    - docker build -t logger-client .
    - docker run -e MQ_CONN_STRING="amqp://guest:guest@172.16.27.7/" --rm logger-client go test
  tags:
    - golang
